client:
  yonder:
    #hostName: https://3390710d-eca5-4c96-ac38-c516306628e0.mock.pstmn.io
    hostName: https://998d8129-2264-4a98-a92e-ba8bde4a4d1c.mock.pstmn.io

supported:
  city: Cluj-Napoca, Bucuresti, Timisoara, Constanta, Baia-Mare, Arad